# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  image  = "bento/ubuntu-20.04"
  
  config.vm.define "manager" do |manager|
    manager.vm.box = image
    manager.vm.hostname = "manager"
    manager.vm.network "public_network"
    manager.vm.network "private_network", ip: "192.168.33.10"
    manager.vm.synced_folder "../Ansible/", "/home/vagrant/Ansible/",
    create: true, owner: "vagrant", group: "vagrant", mount_options: ["dmode=755","fmode=755"]
    manager.vm.synced_folder "../Jenkins/", "/home/vagrant/Jenkins/", 
    create: true, owner: "vagrant", group: "vagrant", mount_options: ["dmode=755","fmode=755"]
    manager.vm.provision "shell" do |s|
      s.path = "provisions/manager.sh"
    end
    manager.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "dev" do |dev|
    dev.vm.box = image
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.33.11"
    dev.vm.provision "shell" do |s|
      s.path = "provisions/dev.sh"
    end
    dev.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end
